### ISSUE TITLE
Webstorm not auto-completing class-validator

### ISSUE THREAD

**Issue by ambroiseRabier** [EndyKaufman/ngx-dynamic-form-builder#103]
Webstorm IDE do not propose me to import the decorators I use from class-validator (and class transformer). Like `@IsNotEmpty()`, my IDE is acting like the package does not exist. But when adding the import manually he recognize it and compile.

It is maybe because ngx-dynamic-for-builder has its own version of class-validator.
Would it not make more sense to have class-validator and class-transformer as peer-dependencies only ?

I worked around the auto-import issue, by adding the class-validator and class-transformer as dependencies of my project.

**Comment by EndyKaufman** [comment]
Newbies do not understand peer-dependencies, and when connecting a library get an error, use a workaround to add dependencies to the correct version in your application.

Maybe I'll clean them later.
