### ISSUE TITLE
Why does the example use @Input() decorators ?

### ISSUE THREAD

**Issue by ambroiseRabier** [EndyKaufman/ngx-dynamic-form-builder#104]
What is the reason for having Input decorators:
```
  @Input()
  form: DynamicFormGroup<Company>;
  @Input()
  item = new Company({
    'id': 11,
    'name': '123456789012345'
  });
```
Are they necessary ? They do not seem to have any use in the example.

**Comment by EndyKaufman** [comment]
Thanks, I added them out of habit, in my projects I often redefine them from the parent, I'll correct the examples later.
