### ISSUE TITLE
How to add multiple fields validators ?

### ISSUE THREAD

**Issue by ambroiseRabier** [EndyKaufman/ngx-dynamic-form-builder#106]
With a normal form build you would do that bellow:
```
this.myForm = fb.group({
  field1: [null],
  field2: [null]
  // more fields 
}, {validator: this.myValidator})
```

```
myValidator(group: FormGroup) {
  let sum = 0;
  for(let a in group.controls) {
    sum += group.get([a]).value;
  }
  return sum > 10 ? { notValid: true} : null
}
```

Signature of function group of DynamicFormBuilder is:
``` 
group<TModel>(factoryModel: ClassType<TModel>, controlsConfig?: FormModel<TModel> | DynamicFormGroupConfig, extra?: DynamicFormGroupConfig): DynamicFormGroup<TModel>;
```
when signature of group function of FormBuilder is:
```
group(controlsConfig: {
        [key: string]: any;
    }, options?: AbstractControlOptions | {
        [key: string]: any;
    } | null): FormGroup;
```

@See https://stackoverflow.com/questions/48704858/angular-5-validate-multiple-input-fields-by-sum-up-values

**Comment by EndyKaufman** [comment]
You may use this example: https://endykaufman.github.io/ngx-dynamic-form-builder/project/step-2
![image](https://user-images.githubusercontent.com/4127109/56087996-80c1d900-5e90-11e9-857c-1614e24a2c0c.png)

Or try use legacy options, but is not work correctly
`
this.form = this.fb.group(User,undefined,{legacyOrOpts:{
      validator: this.myValidator
}});
`

**Comment by ambroiseRabier** [comment]
It seems that is your example you are using https://github.com/typestack/class-validator#validation-groups, this is not what I am looking for.

I have tried:
```
this.form = this.fb.group(User,undefined,{legacyOrOpts:{ validator: this.myValidator }});
```
and also
```
      this.form = this.fb.group<Post>(Post,
        undefined,
        {validator: e => ({ notValid: true})} as any
      );
```

But BOTH return a form that has no errors.

I have looked at https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-builder.ts, `const formGroup = super.group(classValidators, extra);` is fine but you only use that data partially.

You are getting `.controls` and `.valueChanges` but not `.errors`.

You need something like `dynamicFormGroup.errors = formGroup .errors`.

Maybe, to avoid any future similar issue, you can change your code so that you return `formGroup` updated with DynamicFormGroup additionnal functionnality. Instead of extracting one by one results of `super.group()` into resulting `dynamicFormGroup`.

**Comment by EndyKaufman** [comment]
No, sample include not only using groups, i talk about, try use custom validator and nested validate, example:
```
  @ValidateNested()
  @Validate(MyValidator)
  @Type(()=>Task)
  tasks?: Task[] = [];
```

**Comment by ambroiseRabier** [comment]
My object Post isn't nested, it is the root object.

Here is what he look like:
```
export class Post extends BaseModel {
  @IsNotEmpty()
  @IsString()
  @NotEquals('add')
  readonly title: string = '';

  @IsDefined()
  @IsString()
  readonly shortDescription: string = '';

  @IsOptional()
  @IsInt()
  readonly articleId: number|null = null;

  @IsOptional()
  @IsUrl()
  readonly externalLink: string|null = null;

  constructor(post?: Partial<Post>) {
    super();

    plainToClassFromExist(this, post);
  }

  static classLevelValidator(obj: Post): boolean {
    // do not use !! because 0 is equivalent to false :), fuck you js
    return (obj.articleId != null || obj.externalLink != null)
      && (obj.articleId != null) !== (obj.externalLink != null);
  }
}
```

I would like to avoid having to make an intermediary class to be able to used `ValidateNested()`:
```
export class PostContainer {
  @ValidateNested()
  @Validate(MyValidator)
  @Type(()=>Post)
  post: Post;
}
```

class-validator package do not have class level validators as said here: https://github.com/typestack/class-validator/issues/182

I think the best, would be to enable legacy option as explained above, unless there is something I am not aware of ?

**Comment by EndyKaufman** [comment]
After release please check https://endykaufman.github.io/ngx-dynamic-form-builder/project/step-2
