### ISSUE TITLE
form has custom error message for a valid control?

### ISSUE THREAD

**Issue by RudolfSteven** [EndyKaufman/ngx-dynamic-form-builder#121]
I get a confusing situation when validating a formcontrol with @Matches:

When using a regular expression as validation on a form field and put the 'g' modifier on it, then the form control still have customErrors (or formErrors) even if the control is valid. When I remove the 'g' modifier on the regular expression it works perfectly fine.

I adjusted your stackblitz-example to show the situation: https://stackblitz.com/edit/ngx-dynamic-form-builder-qn5zrb  (type 'abc' in the input field. Then the form control is valid but the error message still appears)

I do not know if the 'g' modifier on the regular expression makes sense in that case. But in any case no valid form control should have error messages.

**Comment by jbjhjm** [comment]
I'm experiencing *similar* issues which might be related to this. Though I still need to do further investigation to find out what's happening. In short it looks like the formControl is still being marked as invalid (and so is the form) although it should be valid (and there's no error message available in formGroup.formErrors either.)

**Comment by RudolfSteven** [comment]
@jbjhjm: I had a little time for investigation. 
I face a smiliar problem that the form is INVALID when the model class with the navigation rules have more fields than controls in the formGroup. Then it can happens that a field is INVALID but the form does not contain this field. 

In my opinion these errors should be ignored but the DynamicFormBuilder uses a 'foreverInvalid'-Control to mark the formGroup as INVALID in this case.

You can bypass this behaviour if you add a control 'foreverInvalid' to your formGroup but let this completely untouched. (See [Stackblitz example](https://stackblitz.com/edit/ngx-dynamic-form-builder-blxwo3?file=app%2Fuser-panel%2Fuser-panel.component.ts))

**Comment by EndyKaufman** [comment]
I didn't test regular expressions, thanks for the example, I'll fix it later

**Comment by EndyKaufman** [comment]
Sorry, I could not fix this bug, in the current release, now you may use as ```@Matches(RegExp('^abc$', 'ig'), { message: "it should match the cool 'abc' string" })```
