### ISSUE TITLE
lodash-es usage reasons, unexpected token export 

### ISSUE THREAD

**Issue by kovaletsyurii** [EndyKaufman/ngx-dynamic-form-builder#127]
What is the reason for using lodash-es in the project? Its crashed my build of the Angular universal project with next error:
```
.../node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

SyntaxError: Unexpected token export
```

## part of my package json
```
"@angular/cdk": "^7.1.0",
"@angular/common": "7.1.1",
"@angular/compiler": "7.1.1",
"@angular/core": "7.1.1",
"ngx-dynamic-form-builder": "^0.4.0" 
```

As temporary solution I do 
```
rm -rf ./node_modules/lodash-es && cp -r ./node_modules/lodash ./node_modules/lodash-es
```
before every ng build --prod running; but I want to resolve this problem more correctly.

**Comment by EndyKaufman** [comment]
Hi! try use new version 1.0.0, it is not use lodash-es
https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/package.json

**Comment by kovaletsyurii** [comment]
it`s solve my issue, Thanks @EndyKaufman
