### ISSUE TITLE
Please update dependency class-validator

### ISSUE THREAD

**Issue by jbjhjm** [EndyKaufman/ngx-dynamic-form-builder#153]
class-validator finally introduced tree-shakable validators (since 0.12.0, see [Pull 568](https://github.com/typestack/class-validator/pull/568)). 

This makes it a lot more compact to use and stops requiring hacks to exclude bold dependencies (libphonenumber, hundreds of KB). 
Would you mind to push the version used by dynamic form builder? Thank you :)

Note: I just read about a breaking change which might require changes:
"all validations (except system ones) are type ValidationTypes.CUSTOM_VALIDATION now - mostly internal change"

If I do remember the source of dynamic form builder correctly, it distinguishes between several types.

**Comment by EndyKaufman** [comment]
done

**Comment by jbjhjm** [comment]
Thank you :D
