### ISSUE TITLE
Cannot find module 'ngx-dynamic-form-builder'

### ISSUE THREAD

**Issue by monikaxx** [EndyKaufman/ngx-dynamic-form-builder#156]
We cloned project

npm install
ng serve demo
and got errors as "Cannot find module 'ngx-dynamic-form-builder'." where ever present below import line -

import { DynamicFormBuilder, DynamicFormGroup } from 'ngx-dynamic-form-builder'

**Comment by EndyKaufman** [comment]
hi, try run with 
```
npm run start
```

**Comment by monikaxx** [comment]
Thank you very much.
It worked
