### ISSUE TITLE
feat: support numbers, booleans in formarrays

### ISSUE THREAD

**Issue by codingisnuanced** [EndyKaufman/ngx-dynamic-form-builder#159]
I noticed this at [L414](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L414)

`if (value && Object.keys(value).length > 0) {
                object[key].push(value);
              }`

This is under `getObject` -> `else if (this.controls[key] instanceof FormArray)`. The story here is that an object of class type `TModel` is created from the controls' values. Besides the fact that null values may be desired in the object's array, this simply ignores numbers as values i.e. I need to create an array of numbers in the object.

When `.validate` ([L121](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L121)) is called, it invokes `this.object` ([L129](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L129)) which, in turn, invokes `getObject`. The validation result will, therefore always return errors when a form array of primitive numbers is used when it is expected that it be populated, as per the validation decorators present.

**Comment by codingisnuanced** [comment]
It also targets empty strings. These value victims should be handled by the validation decorators.

**Comment by EndyKaufman** [comment]
hi, ok I try to support this feature later

**Comment by EndyKaufman** [comment]
Hi @codingisnuanced, why you need this feature,? please add example of usage

**Comment by EndyKaufman** [comment]
done, try it in https://endykaufman.github.io/ngx-dynamic-form-builder/new-api
