### ISSUE TITLE
feat: support empty form array

### ISSUE THREAD

**Issue by codingisnuanced** [EndyKaufman/ngx-dynamic-form-builder#160]
I noticed on [L322](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L322) that the else clause assumes the form array must contain at least one element. Similar to #159, empty arrays should be supported. Currently, form-building with an empty form array i.e. `this.dfb.array([])` fails. I suggest wrapping [L317](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L317) to [L325](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L325) in `if ((fields[key] as FormArray).controls[0] != undefined) {`

**Comment by codingisnuanced** [comment]
Also, I think `onlyFields` at L316, which contains the issue above, assumes that all elements of a form array must be of the same type. This would ignore the fields of one of the types in `(number | MyClass)[]` for example.

**Comment by EndyKaufman** [comment]
done, try it in https://endykaufman.github.io/ngx-dynamic-form-builder/new-api
