### ISSUE TITLE
fix: use value from getObject if parent is a group object

### ISSUE THREAD

**Issue by codingisnuanced** [EndyKaufman/ngx-dynamic-form-builder#161]
In `setObjectValueAndGetValidationErrors(fieldName, control, validationOptions)` at [L882](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L882), the object is retrieved from the parent if the parent is `DynamicFormGroup`, but the value at `fieldName` in the retrieved object is immediately replaced at [L900](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L900). This would go on to fail validation in a pesky manner if the class/factoryModel of the parent uses `@Type` or `@Transform` and the likes from [class-transformer](https://github.com/typestack/class-transformer). For example, if the input from the UI gives a string, and the property to which it is bound in the factory model is expected to be transformed to a number before other validators can take effect, [L900](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L900) would replace the transformed data and go on to fail with the call to `getValidationErrors` at [L903](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L903). The error is rather hidden; I found it in the `nativeValidateErrors` BehaviorSubject (.value) as a customValidation error. Both `formErrors` and `errors` were null in this case.

I suggest the following to replace [L893](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L893) to [L902](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L902):
`let object;
  if (control.parent instanceof DynamicFormGroup) {
    object = (control.parent as DynamicFormGroup<any>).object;
  } else if (control.parent) {
    object = control.parent.value;
    object[fieldName] = control.value;
  } else {
    object = {};
    object[fieldName] = control.value;
  }`

**Comment by EndyKaufman** [comment]
library rewrited, try it in https://endykaufman.github.io/ngx-dynamic-form-builder/new-api
