### ISSUE TITLE
feat: support arrays with multiple types

### ISSUE THREAD

**Issue by codingisnuanced** [EndyKaufman/ngx-dynamic-form-builder#162]
`onlyFields` at [L316](https://github.com/EndyKaufman/ngx-dynamic-form-builder/blob/develop/libs/ngx-dynamic-form-builder/src/lib/utils/dynamic-form-group.ts#L316), which contains the issue #160 , assumes that all elements of a form array must be of the same type. This would ignore the fields of one of the types in `(number | MyClass)[]`, for example.

**Comment by EndyKaufman** [comment]
done, try it in https://endykaufman.github.io/ngx-dynamic-form-builder/new-api
