### ISSUE TITLE
Array validation ({each:true})

### ISSUE THREAD

**Issue by jbjhjm** [EndyKaufman/ngx-dynamic-form-builder#169]
Hi there, 
I was getting some weird behavior, did some debugging, and found out my installed dynamic form builder does not support array-mode of validators (by setting options.each = true). 

Was going to make a pull request but then realized your implementation has changed drastically since the version that I'm still using (1.3.5). (Stuck because recent class-validator does not offer global i18n.)

So possibly this issue is already resolved in newest version.
Just to be sure and help if it is not, I thought I'd just let you know about the needed code change.

In `createDynamicValidate`, replace
```ts
const isValid = control.parent && control.parent.value
	? validator.validateValueByMetadata(control.value, validationMetadata)
	: true;
```
by
```ts
let isValid = true;
function convertToArray(val) {
	if (val instanceof Map) {
		return Array.from(val.values());
	}
	return Array.isArray(val) ? val : Array.from(val);
}

if (control.parent && control.parent.value) {
	const value = control.value;
	if (validationMetadata.each) {
		if (value instanceof Array || value instanceof Set || value instanceof Map) {
			var arrayValue = convertToArray(value);
			isValid = arrayValue.every(function (subValue) { 
				return validator.validateValueByMetadata(subValue, validationMetadata); 
			});
		}
	}
	else {
		isValid = validator.validateValueByMetadata(value, validationMetadata);
	}
}

```
which reimplements the code used in ValidationExecutor.defaultValidations.

If this is outdated due to different implementation feel free to close.

## Edit: Example

```ts
ExampleClass {
	@IsString()
	prop1:string

	@IsString({each:true})
	list:string[];
}
```

Without this change, dto.list would not validate correctly, while prop1 does.
The change shown above adds the code responsible for iterating over Array from class-validator.

**Comment by EndyKaufman** [comment]
Hi, please add example of dto with not work logic

**Comment by jbjhjm** [comment]
@EndyKaufman Added example to end of first post!

**Comment by EndyKaufman** [comment]
I create PR to class validator for support i18n

https://github.com/typestack/class-validator/pull/728

**Comment by EndyKaufman** [comment]
my pr not resolved, I change class-validator to class-validator-multi-lang for support i18n
