### ISSUE TITLE
Question: How to use Angular async validators with ngx-dynamic-form-builder?

### ISSUE THREAD

**Issue by tscislo** [EndyKaufman/ngx-dynamic-form-builder#173]

**Comment by EndyKaufman** [comment]
Hi, for this case I use external errors, sample https://endykaufman.github.io/ngx-dynamic-form-builder/advanced

**Comment by tscislo** [comment]
@EndyKaufman sorry but I don't know what you mean by "external errors"

I know that it is possible to create custom async validator using class-validator, like this:

`
import {
  registerDecorator,
  ValidationOptions,
  ValidatorConstraint,
  ValidatorConstraintInterface,
  ValidationArguments,
} from 'class-validator';

@ValidatorConstraint({ async: true })
export class IsUserAlreadyExistConstraint implements ValidatorConstraintInterface {
  validate(userName: any, args: ValidationArguments) {
    return UserRepository.findOneByName(userName).then(user => {
      if (user) return false;
      return true;
    });
  }
}

export function IsUserAlreadyExist(validationOptions?: ValidationOptions) {
  return function (object: Object, propertyName: string) {
    registerDecorator({
      target: object.constructor,
      propertyName: propertyName,
      options: validationOptions,
      constraints: [],
      validator: IsUserAlreadyExistConstraint,
    });
  };
}`

However there is a problem Angualr Dependency Injection as this is not angular service to which we can inject for example Http service.

**Comment by EndyKaufman** [comment]
Asynchronous validators are heavy, both in the nestjs node and in angular

I just never use them when I need a similar feature - I use external errors

**Comment by tscislo** [comment]
@EndyKaufman 
So basically ngx-dynamic-form-builder does not support async validators?

Do you have any example of external errors approach in Angular?

**Comment by EndyKaufman** [comment]
https://endykaufman.github.io/ngx-dynamic-form-builder/advanced

**Comment by EndyKaufman** [comment]
real example from my pet project
```
import { Injectable } from '@angular/core';
import { DynamicFormGroup, transformValidationErrors } from 'ngx-dynamic-form-builder';
import { NGXLogger } from 'ngx-logger';
import { ToastContainerDirective, ToastrService } from 'ngx-toastr';
import { EMPTY, Observable, of, throwError } from 'rxjs';
import { catchError, tap } from 'rxjs/operators';

@Injectable({ providedIn: 'root' })
export class CoreFormProcessorService {
    public toastId: number;
    constructor(private readonly logger: NGXLogger, private toastr: ToastrService) {}

    hideToaster(): void {
        if (this.toastId) {
            this.toastr.clear(this.toastId);
        }
    }

    showSuccessToaster(options: { successMessage: string; overlayContainer?: ToastContainerDirective | undefined }): void {
        let positionClass = 'toast-top-right';
        if (options.overlayContainer) {
            this.toastr.overlayContainer = options.overlayContainer;
            positionClass = 'inline';
        }
        this.toastId = this.toastr.success(options.successMessage, undefined, {
            progressBar: true,
            positionClass,
        }).toastId;
    }

    showErrorToaster(err: any, options: { errorMessage?: string | undefined; overlayContainer?: ToastContainerDirective | undefined }): void {
        const error = this.extractError(err);
        let positionClass = 'toast-bottom-right';
        if (options.overlayContainer) {
            this.toastr.overlayContainer = options.overlayContainer;
            positionClass = 'inline';
        }
        this.toastId = this.toastr.error(options.errorMessage || error.message, undefined, {
            progressBar: true,
            positionClass,
        }).toastId;
    }

    process<TRequest, TResponse>(
        form: DynamicFormGroup<TRequest>,
        handler: () => Observable<TResponse>,
        options: { successMessage: string; errorMessage?: string; overlayContainer?: ToastContainerDirective }
    ): Observable<TResponse | null> {
        form.validateAllFormFields();
        // eslint-disable-next-line no-constant-condition
        if (form.valid) {
            form.setExternalErrors([]);
            return handler().pipe(
                catchError((err) => {
                    const error = this.extractError(err);

                    if (error.validationErrors) {
                        form.setExternalErrors(transformValidationErrors(error.validationErrors));

                        return EMPTY;
                    }
                    if (options.errorMessage || error.message) {
                        this.showErrorToaster(err, options);

                        return EMPTY;
                    }

                    return throwError(() => err);
                }),
                tap(() => {
                    this.showSuccessToaster(options);
                }),
                tap(() => form.setExternalErrors([]))
            );
        } else {
            this.logger.log(form.customValidateErrors.value);
            return of(null);
        }
    }

    extractError(err: any): any {
        return err?.graphQLErrors?.[0] || err?.networkError?.error?.errors?.[0] || err?.error || err;
    }
}
```
and then use as
```
this.signInForm.json = { ...this.signInForm.json, fingerprint };
                    return this.coreFormProcessorService.process(this.signInForm, () => this.authRestService.authControllerSignIn(this.signInForm.json), {
                        successMessage: this.translocoService.translate('Sign in was successful!'),
                    });
```

**Comment by tscislo** [comment]
@EndyKaufman thanks!
So basically you're doing this manually using Reactive Forms approach and not using any decorators, which I think is something I would expect to have.

Power to ngx-dynamic-form-builder is that it allows for declarative validation definition. With your approach for async we're going back to using Reactive Forms the "old way", which is not very declarative.

**Comment by EndyKaufman** [comment]
in earlier versions it was, but it led to many bugs, the current lib converts the validator class of the rule into the angular of the validation rule, but the logic for asynchronous validators changed into the angular and the code became incompatible with the validator class, and I removed it

**Comment by tscislo** [comment]
@EndyKaufman I understand, thank you. Maybe it would be good to concider reimplementing it? Any plans?

**Comment by EndyKaufman** [comment]
I have thought several times already and tried to implement, but it is difficult, I will try again :)

**Comment by EndyKaufman** [comment]
done, try it in https://endykaufman.github.io/ngx-dynamic-form-builder/new-api
