### ISSUE TITLE
Update to Angular v13

### ISSUE THREAD

**Issue by ProgressiveDev** [EndyKaufman/ngx-dynamic-form-builder#179]
Hey, just wanted to know if there is a plan to update to Angular 13? There are some packages like class-validator not building on Angular 13 since this project requires angular 11.0.9.

**Comment by EndyKaufman** [comment]
I already did it locally, I am writing e2e tests now, but the dependencies will be different

Part of new readme...
## BREAKING CHANGE

Version above 2 has a completely rewritten code, partially backwards compatible

Now `@Expose` and `@Exclude` decorators are used to define model fields, the new version is rigidly dependent on class-transform

Dependencies are not used original, but forks with additional necessary properties, when using this library, you need to replace all original imports with forks with modifications

Fork [class-validator-multi-lang](https://github.com/EndyKaufman/class-validator-multi-lang) - adds translation capability for errors (PR:[https://github.com/typestack/class-validator/pull/743](https://github.com/typestack/class-validator/pull/743))

Fork [class-transformer-global-storage](https://github.com/petrzjunior/class-transformer) - adds the ability to get meta information about all used classes (PR:[https://github.com/typestack/class-transformer/pull/929](https://github.com/typestack/class-transformer/pull/929))

**Comment by ProgressiveDev** [comment]
any estimates on release?

**Comment by EndyKaufman** [comment]
maybe 1-2 days

**Comment by EndyKaufman** [comment]
done
