### ISSUE TITLE
v2: "Greedy" creation of nested Models causes recursive errors and unexpected creation of submodels

### ISSUE THREAD

**Issue by jbjhjm** [EndyKaufman/ngx-dynamic-form-builder#185]
## Issue description

Edit: Added more thorough information on the issue.

v2 introduces a different submodel handling.
Its behaviour is "greedy" now.

Example: 
```ts
		class Company {
			@Expose()
			name: string;
			@Expose()
			@Type(()=>User)
			manager:User;
		}
	
		class User {
			@Expose()
			name: string;
	
			@Type(type => Company, {})
			@Expose()
			optCompany?: Company = undefined;
		}
```

 The above sample will
- crash with call stack error because getMetadata() will recursively loop between User.optCompany and Company.manager
- if recursiveness is limited, It would still assign a new Company model to optCompany, even though class-transformer would default it to undefined

This was not the case with DFB v1.

I checked the getMetadata function but could not find anything hinting to an existing mechanism to prevent this behavior.

## Solutions

a) specify a max. depth for submodel creation. ~If a model has multiple submodels, it might become difficult to use this method as it lacks precise configuration~ Not a solid solution, but can at least prevent app freezes / call stack exceeded errors.

b) detect if a model circularly references itself and abort creation in that case. Insufficient solution because it's unconfigurable, it would only help to prevent some bad errors.

c) pass contextual information on which submodels should be created greedily and which models are optional.
In addition to that, this must also work for sub-submodels and possibly there is even need to distinguish between if the model is being created as a first-level-submodel or a 1+n-level-submodel.

## Next

I really need to fix this as fast as possible, so I'm currently working on implementing it.
a) makes sense for preventing recursiveness,
but only
c) would really be able to provide a solution to the issue.

**Comment by jbjhjm** [comment]
Looks like it is closely related to a recent change in class-transformer which changes transformation behavior to always create models specified by `@Type(()=>MyModelConstructor)` even if the property value is undefined or null.

https://github.com/typestack/class-transformer/issues/1086

Summarizing, it is possible that the issue will be gone when class-transformer behavior has been fixed.

**Comment by EndyKaufman** [comment]
I also thought about such a case, but I decided that few people do this) it means I was wrong, today I’ll think about how to solve it, correcting the behavior of class-transforms will not eliminate the error if there is no null

thanks for issue

**Comment by jbjhjm** [comment]
@EndyKaufman thanks for the quick response.
I'm right now writing tests for a PR.
I decided Decorators are a bad way to go because we should not assume that a model is always going to be used in the same way in all forms that use it.

For this reason, my concept looks like this:
DynamicFormBuilderOptions get an additional prop named allowedNestedModels.
Only if it is defined, behavior will change.
It is a list of strings, each being a property path.

Referring to my above example,
* rootFormGroup(User,{},{allowedNestedModels:undefined}) would use the known, existing behavior (allowedNestedModels defaults to undefined)
* allowedNestedModels=[] would create no submodels at all
* rootFormGroup(User,{},{allowedNestedModels=['company']}) would create a User with Company submodel at root.company, but no submodels within company
* rootFormGroup(User,{},{allowedNestedModels=['company','company.manager']}) would additionally auto-create a User entity at root.company.manager, but no other company at root.company.manager.company.

Essentially this solution is going to allow us to specify manually which submodels to create and which to omit.

**Comment by EndyKaufman** [comment]
I create an issue https://github.com/EndyKaufman/ngx-dynamic-form-builder/issues/186 for me to add all needed tests, after it, I take this issue, for correct update core logic
estimate: 1-3 days

**Comment by EndyKaufman** [comment]
@jbjhjm 
export class Company {
...
  @ValidateNested()
  @Type(() => Department)
  @Expose({ groups: ['nested'] })
  department?: Department | undefined;
...
}
...
    this.form = this.formBuilder.rootFormGroup(
      Department,
      this.getEmptyDepartment(),
      {
        classTransformOptions: {
          excludeGroups: ['nested'],
        },
      }
    );
...
