### ISSUE TITLE
v2: Does not respect @IsOptional props

### ISSUE THREAD

**Issue by jbjhjm** [EndyKaufman/ngx-dynamic-form-builder#188]
Oh dear, I found another one :O 
Using a model like

```ts
class User {
  @Expose()
  name:string;
  @IsOptional()
  @Expose()
  @IsEmail({})
  email:string;
}
```

customValidateErrors will always contain an error for User.email.

Though with @IsOptional being set, validation should be skipped if email is undefined or null (and possibly empty string, too).

**Comment by jbjhjm** [comment]
Another unexpected behavior: form.statusChanges emits VALID even though there are customValidateErrors.
It seems this happens if the only customValidateErrors are on fields that haven't been touched so far.

I don't know if statusChanges was intended to work correctly or if it is recommended to only subscribe to customValidateErrors instead. If so, I suggest to add to documentation which features of the original FormGroup should not be used.

**Comment by EndyKaufman** [comment]
error with IsOptional - fixed, about statusChanges please create example with fork https://stackblitz.com/edit/ngx-dynamic-form-builder-new-api

**Comment by EndyKaufman** [comment]
@jbjhjm

**Comment by jbjhjm** [comment]
Thanks @EndyKaufman ! About reproduction, it will take a some time before I can free some time to write one. Will let you know then!
