### ISSUE TITLE
setObject -- inconsistent behavior on FormArrays

### ISSUE THREAD

**Issue by jbjhjm** [EndyKaufman/ngx-dynamic-form-builder#195]
Don't whack me please :'D I think I found another small bug.

setObject seems to handle FormArrays and FormGroups differently:
* For FormGroups, patched values will be replaced by new values.
* For FormArrays, new values will be ADDED to patched values.

So let's assume we have a Dynamic FormGroup set up with data like this:

```ts
{
  name:'foo',
  attachments:[
    {name:'test',file:'path'},
    {name:'stuff',file:'path2'}
  ]
}
```

And then run

```ts 
formGroup.setObject({
  name:'bar',
  attachments:[
    {name:'changed',file:'newpath'},
    {name:'stuff',file:'path2'}
  ]
})
```

the form value will become

```ts
{
  name:'bar',
  attachments:[
    {name:'test',file:'path'},
    {name:'stuff',file:'path2'},
    {name:'changed',file:'newpath'},
    {name:'stuff',file:'path2'}
  ]
}
```

the naming `setObject` indicates the whole form value will be replaced, in opposite to something like `patchObject`.
So I think the current behavior is inconsistent and existing FormArray items should be cleared before adding new controls.

**Comment by EndyKaufman** [comment]
@jbjhjm  it's not a bug, it's a feature :) I'll think about how to solve it

**Comment by jbjhjm** [comment]
@EndyKaufman ahhh ok I see :) It was a bit unexpected for me.
Logical solutions would be to 
* add a `patchObject` method or 
* allowing configuration like `setObject(data,{patchArrays:true})`.

For now I'll iterate the root formGroup and clear array entries before repatching.
This could be packed into a method like `resetAllFormArrays`.
Then however, the behavior of setObject should be documented accordingly so that noone stumbles upon this.

**Comment by EndyKaufman** [comment]
@jbjhjm solved in new version https://github.com/EndyKaufman/ngx-dynamic-form-builder/releases/tag/v2.2.1
