### ISSUE TITLE
Angular 14 dependecy update

### ISSUE THREAD

**Issue by RushPVA** [EndyKaufman/ngx-dynamic-form-builder#213]
Current version is linked to angular v13. Could you please update to version 14?

**Comment by EndyKaufman** [comment]
ok)

**Comment by RushPVA** [comment]
Thanks a lot!

**Comment by EndyKaufman** [comment]
I updated to version 15

**Comment by RushPVA** [comment]
@EndyKaufman will it work wuth both 14 and 15? or just with 15?

**Comment by EndyKaufman** [comment]
I think it will work, I didn’t change anything in the code, I just bumped the dependencies

**Comment by EndyKaufman** [comment]
all my projects are now on the 13th Angular, have not been updated for new versions yet

**Comment by RushPVA** [comment]
@EndyKaufman I have tested, i am unable to run 'npm install' without --force because 2.3.0 is linked to angular v15. could you please add support of both v14 and v15, or maybe do additional release just for v14?

**Comment by RushPVA** [comment]
Cool. Thanks a lot!

**Comment by EndyKaufman** [comment]
please try version 2.3.1, and give answear if it work

**Comment by RushPVA** [comment]
@EndyKaufman No, it doesn't work(
![изображение](https://user-images.githubusercontent.com/2292336/203987955-abdc348d-7090-4cc9-b606-e6bff09020f8.png)

**Comment by RushPVA** [comment]
@EndyKaufman supppose all dependencies need to be updated
![изображение](https://user-images.githubusercontent.com/2292336/203988756-208c8ba0-2d39-4a56-a99f-42fe5e0d26ba.png)

**Comment by EndyKaufman** [comment]
please check version 2.3.2 )

**Comment by RushPVA** [comment]
@EndyKaufman No, it doesn't work)
![изображение](https://user-images.githubusercontent.com/2292336/203993275-aed4d73c-e108-45e9-b19a-a3e4efb615e7.png)

**Comment by EndyKaufman** [comment]
sorry i missed one dependency

**Comment by RushPVA** [comment]
2.3.3. It works! Thank you a lot!
