### ISSUE TITLE
Refactor proposal: Code organization and cleanup prior to feature PRs

### ISSUE THREAD

**Issue by ScottMGerstl** [EndyKaufman/ngx-dynamic-form-builder#81]
Co-workers and I have a need to access all the applied validation on form controls at the point they are created (currently, only the invalid validators can be dynamically retrieved at this point) for dynamic UI purposes. 

We would also appreciate a simplified API for for errors.

In preparation for writing these features, while reading through the code, I organized it and documented it to help me pick out what the code is doing at a glance. 

I have submitted PR #80 with this refactor in case you would like to take advantage of the organization.

I understand that I may have a different style of coding than you and would be happy to make any changes based on your style guide. I tried to keep as much of your style while helping with readability for my co-workers and I. 

If you choose not to accept this PR, we will maintain our own fork.

I have noted the changes with comments on the PR as the re-organization may make it difficult to track.

*TESTING*
I have tested for parody with your most current online demo and have found that everything works the same except the Task description on FormArray and Steps. 

- In your hosted example, the description is marked immediately invalid when a new description is added and is empty. 
- In my code, it will not mark it immediately invalid but, if you put a value in and then remove it, it is marked as invalid. If you could direct me to which function is responsible for this, I can further debug and fix the issue.

**Comment by EndyKaufman** [comment]
Hi, thank you for the great work done, I am now trying to find and correct the error of array validation, as this is important to me first of all. 
If you correct before me, I will accept the pull request.
The error is most likely in the method: getClassValidators

**Comment by EndyKaufman** [comment]
merged pull request and fix it with https://github.com/EndyKaufman/ngx-dynamic-form-builder/commit/bf296c36af0ad28c6d02a4f63b63974709e3433e
