### ISSUE TITLE
Feature proposal: Create a non-observable API for errors

### ISSUE THREAD

**Issue by ScottMGerstl** [EndyKaufman/ngx-dynamic-form-builder#83]
Angular's change detection can handle the changes in the form errors without the use of an observable. I would like to propose introducing `formErrors: ShortValidationErrors` to the dynamic-form-group that is read into at the same point that the observable's next function is called.

A user will then be able to access the errors in the view or code through `form.formErrors` instead of `(form.customValidateErrors | async)` or `await this.form.customValidateErrors.toPromise();` (or any other observable handling strategies).

I have opened PR #82 which is intended to be reviewed and merged after PR #81 (code refactor: organization and documentation). 

You can see the feature specific code changes in this comparison between my branches: https://github.com/ScottMGerstl/ngx-dynamic-form-builder/compare/refactor/organization-n-documentation...ScottMGerstl:feature/sync-form-errors

**Comment by EndyKaufman** [comment]
Thank you, for you work :+1:
