### ISSUE TITLE
Feature Proposal: Add validation definitions to FormControls

### ISSUE THREAD

**Issue by ScottMGerstl** [EndyKaufman/ngx-dynamic-form-builder#85]
Proposal to add the class-validator metadata to the form controls it is applied to allowing the validation rules that are applied to the form control to be inspected at any point during runtime. Currently, in Angular, during runtime, only invalid rules are available at any given runtime 

I have opened PR #84 which is intended to be reviewed and merged after PR #81 (code refactor: organization and documentation).

You can see the feature specific code changes in this comparison between my branches: https://github.com/ScottMGerstl/ngx-dynamic-form-builder/compare/refactor/organization-n-documentation...ScottMGerstl:feature/validation-on-controls

**Comment by EndyKaufman** [comment]
Sorry for dropping your changes on getClassValidators, can you implement changes in isolation for DynamicFormControl to work correctly?

**Comment by ScottMGerstl** [comment]
I certainly can. I should have that to you in a few hours

**Comment by ScottMGerstl** [comment]
Closed initial PR. Replaced it with PR #87.
