### ISSUE TITLE
Bug: regionNum inconsistency between examples (group versus no group?)

### ISSUE THREAD

**Issue by ScottMGerstl** [EndyKaufman/ngx-dynamic-form-builder#89]
In the demo, on the advanced tab and experimental tabs, the `regionNum` has the following configuration: 

```typescript
@IsOptional()
@Min(1)
@Max(99)
regionNum: number;
```

In the Advanced example, if you type in a number greater than 99 or less than 1, you get an error.

In the Experimental example, not matter what value is provided, there is no error

**Comment by EndyKaufman** [comment]
no, this is not a bug, this is a feature :) 
because in experimental  validate only by set groups, if groups did not set validate all fields
```
    this.form = this.fb.group(ExpUser, {
      customValidatorOptions: {
        groups: ['user']
      }
    });
```
for all fields:
```
    this.form = this.fb.group(ExpUser);
```
isolated example: https://stackblitz.com/edit/typescript-hcxynt

**Comment by ScottMGerstl** [comment]
I was unsure of the desired behavior here. I recorded it in case it was wrong. If it's desired, I have no issue with it being closed

**Comment by EndyKaufman** [comment]
Ok, thanks
